### ISSUE TITLE
Restore for bitbucket repo

### ISSUE THREAD

**Issue by cloudsec09** [christianspecht/scm-backup-docs#5]
I am trying to restore according to given instruction but not able to see real content that should be. 

Any detailed instruction?

So I am doing clone for the bare repo to another and when doing commit then cant even see any file. I tried with multiple repo.

**Comment by christianspecht** [comment]
[Restoring your backups](https://docs.scm-backup.org/en/latest/restore.html) are the only available instructions.

Can you explain your actual problem in more detail?
What happens after you cloned the bare repo, does the clone have a working directory?

**Comment by christianspecht** [comment]
Closed for inactivity
